CREATE DATABASE QuanLyQuanCafe
GO

USE QuanLyQuanCafe
GO

CREATE TABLE TableFood
(
ID INT IDENTITY PRIMARY KEY,
NAME NVARCHAR(100) NOT NULL DEFAULT N'ch?a ??t tên',
STATUS NVARCHAR(100) NOT NULL DEFAULT N'Tr?ng',

)
GO

CREATE TABLE ACCOUNT
(
USERNAME NVARCHAR(100) PRIMARY KEY,
DISPLAYNAME NVARCHAR(100) NOT NULL DEFAULT N'ch?a ??t tên',
PASSWORD NVARCHAR(1000) NOT NULL DEFAULT 0,
TYPE INT NOT NULL DEFAULT 0
)
GO

CREATE TABLE FOODCATEGORY
(
ID INT IDENTITY PRIMARY KEY,
name NVARCHAR(100) DEFAULT N'ch?a ??t tên'
)
GO

CREATE TABLE FOOD
(
ID INT IDENTITY PRIMARY KEY,
NAME NVARCHAR(100) NOT NULL DEFAULT N'ch?a ??t tên' ,
IDCATEGORY INT NOT NULL,
PRICE INT NOT NULL DEFAULT 0
FOREIGN KEY (IDCATEGORY) REFERENCES dbo.FOODCATEGORY(ID)
)
GO

CREATE TABLE BILL
(
ID INT IDENTITY PRIMARY KEY,
DATECHECKIN DATE NOT NULL DEFAULT GETDATE(),
DATECHECKOUT DATE,
IDTABLE INT NOT NULL,
STATUS INT NOT NULL DEFAULT 0
FOREIGN KEY (IDTABLE) REFERENCES dbo.TABLEFOOD(ID)
)
GO

CREATE TABLE BILLINFO
(
ID INT IDENTITY PRIMARY KEY,
IDBILL INT NOT NULL,
IDFOOD INT NOT NULL,
COUNT INT NOT NULL DEFAULT 0
FOREIGN KEY (IDBILL) REFERENCES dbo.BILL(ID),
FOREIGN KEY (IDFOOD) REFERENCES dbo.FOOD(ID)
)
GO


INSERT INTO dbo.ACCOUNT
	( UserName,
	DisplayName,
	Password,
	Type
	)
VALUES ( N'K9', 
		N'RongK9',
		N'1',
		1
		)

INSERT INTO dbo.ACCOUNT
	( UserName,
	DisplayName,
	Password,
	Type
	)
VALUES ( N'staff', 
		N'Nhân viên',
		N'1',
		0
		)
GO

CREATE PROC USP_GetAccountByUserName
@userName nvarchar(100)
AS
BEGIN 
	SELECT * FROM dbo.ACCOUNT WHERE UserName = @userName
END
GO

GO
CREATE PROC USP_Login
@userName nvarchar(100), @passWord nvarchar(100)
AS
BEGIN
	SELECT * FROM dbo.ACCOUNT WHERE UserName = @userName AND PassWord = @passWord
END
GO